### ISSUE TITLE
您好，在使用sdk时因为game_id为空log报了个错误

### ISSUE THREAD

**Issue by RemKeeper** [VTB-LINK/bianka#1]
![image](https://github.com/VTB-LINK/bianka/assets/78486275/c31c5fc4-94a6-4bbf-a98b-7b14e8ab5cab)

但是普通的不带定制礼物的项目Star后，B站返回的game_id就是空
![image](https://github.com/VTB-LINK/bianka/assets/78486275/686148f2-8ecd-46b1-a742-628fc87fbc4c)

请问需要另外处理吗，我看源码是没发现会触发重连之类的

**Comment by RunsTp** [comment]
已确认，如果`/v2/app/start` 返回的`game_id`为空，可以无需项目心跳，仅使用长链心跳即可。
